version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.22-git
    parameters:
      revision:
        type: string
        default: rev2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run QMK container and compile keymap
          command: |
            export
            cd /app;
            docker run -d --rm --name qmk qmkfm/qmk_cli sleep 300;
            docker exec -it qmk python3 -m pip install qmk
            docker exec -it qmk qmk setup -y
            docker exec -it qmk python3 -m pip install -r /qmk_firmware/requirements.txt
            docker exec -it qmk qmk env
            docker cp lassieee qmk:qmk_firmware/keyboards/splitkb/kyria/keymaps/
            docker exec -it qmk qmk compile -kb splitkb/kyria/<< parameters.revision>> -km lassieee
            docker cp qmk:/qmk_firmware/splitkb_kyria_<< parameters.revision >>_lassieee.hex .
            docker stop qmk
      - store_artifacts:
          path: /app/splitkb_kyria_rev2_lassieee.hex
      - persist_to_workspace:
          root: /app
          paths:
            - splitkb_kyria_rev2_lassieee.hex

  publish:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - attach_workspace:
          at: /app
      - run:
          name: "Publish release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(git tag | sort -V | tail -1)  /app/splitkb_kyria_rev2_lassieee.hex

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\-\d+\-\d+\.\d+$/

